### ISSUE TITLE
proxychains-4.12 random crash (triggered by signal)

### ISSUE THREAD

**Issue by xuefer** [rofl0r/proxychains-ng#326]
$ gdb  staging_dir/host/bin/bash  bin/packages/x86_64/packages/core

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000043e590 in ?? ()
[Current thread is 1 (Thread 0x7ffff7f7b700 (LWP 6355))]
(gdb) bt
#0  0x000000000043e590 in ?? ()
#1  0x00000000004422e3 in ?? ()
#2  <signal handler called>
#3  0x00007ffff7e2dfef in select () from /lib64/libc.so.6
#4  0x00007ffff7f82471 in wait_data (readfd=<optimized out>) at src/allocator_thread.c:164
#5  getmessage (dir=<optimized out>, hdr=0x7ffff7f7ad98, data=0x7ffff7f7adc8) at src/allocator_thread.c:192
#6  0x00007ffff7f826a2 in threadfunc (x=<optimized out>) at src/allocator_thread.c:210
#7  0x00007ffff7d0c508 in start_thread () from /lib64/libpthread.so.0
#8  0x00007ffff7e3757f in clone () from /lib64/libc.so.6

(gdb) bt full
#0  0x000000000043e590 in ?? ()
No symbol table info available.
#1  0x00000000004422e3 in ?? ()
No symbol table info available.
#2  <signal handler called>
No symbol table info available.
#3  0x00007ffff7e2dfef in select () from /lib64/libc.so.6
No symbol table info available.
#4  0x00007ffff7f82471 in wait_data (readfd=<optimized out>) at src/allocator_thread.c:164
        fds = {fds_bits = {2147483648, 0 <repeats 15 times>}}
        ret = <optimized out>
        __d1 = <optimized out>
        __d0 = <optimized out>
        emsg = <optimized out>
        e = <optimized out>
        x = <optimized out>
#5  getmessage (dir=<optimized out>, hdr=0x7ffff7f7ad98, data=0x7ffff7f7adc8) at src/allocator_thread.c:192
        readfd = {0x7ffff7fcc7c8 <req_pipefd>, 0x7ffff7fcc7d0 <resp_pipefd>}
        ret = <optimized out>
#6  0x00007ffff7f826a2 in threadfunc (x=<optimized out>) at src/allocator_thread.c:210
        msg = {msgtype = ATM_GETIP, datalen = 0}
        ret = <optimized out>
        readbuf = <optimized out>
#7  0x00007ffff7d0c508 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#8  0x00007ffff7e3757f in clone () from /lib64/libc.so.6
No symbol table info available.
(gdb)

**Comment by rofl0r** [comment]
may i suggest trying the latest version ?

**Comment by rofl0r** [comment]
please reopen this if the issue still occurs with latest git master.

**Comment by rofl0r** [comment]
please reopen this if the issue still occurs with latest git master.

**Comment by rofl0r** [comment]
x
