### ISSUE TITLE
Some application on Mac OS X 12.3.1 M1  can't be used with 4.16

### ISSUE THREAD

**Issue by ldzhjn** [rofl0r/proxychains-ng#451]
When I try to list the topics from a Kafka cluster using the following shell wrapped java application, it throws exception.
proxychains4 ~/Downloads/kafka_2.11-2.3.0/bin/kafka-topics.sh --list --bootstrap-server server:port

[proxychains] config file found: /opt/homebrew/etc/proxychains.conf
[proxychains] preloading /opt/homebrew/Cellar/proxychains-ng/4.16/lib/libproxychains4.dylib
[2022-05-17 08:28:16,061] WARN Couldn't resolve server server:port from bootstrap.servers as DNS resolution failed for server:port (org.apache.kafka.clients.ClientUtils)
Exception in thread "main" org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:407)
	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:55)
	at kafka.admin.TopicCommand$AdminClientTopicService$.createAdminClient(TopicCommand.scala:165)
	at kafka.admin.TopicCommand$AdminClientTopicService$.apply(TopicCommand.scala:169)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:55)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88)
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47)
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:367)

But this same command works on Intel CPU Mac OS X 12.3.1 with 4.16.

https://github.com/apache/kafka/blob/trunk/bin/kafka-topics.sh

**Comment by rofl0r** [comment]
please paste `config.mak` that's generated after running configure on both archs (and make sure to build and test master on each)

**Comment by ldzhjn** [comment]
Works after following 
https://github.com/rofl0r/proxychains-ng/issues/78#issuecomment-453510341
https://github.com/rofl0r/proxychains-ng/issues/433#issuecomment-1030753210

**Comment by rofl0r** [comment]
> have 'arm64e', need 'x86_64'

this is the reason. your "kafka" binary is compiled for intel and executed via rosetta binary translation. therefore arm64e proxychains cant be injected.

2 solutions exist:
- get a kafka version compiled for m1
- make a fat binary for x86_64 and arm64e: it should work like this: `CFLAGS="-arch x86_64 -arch=arm64e" LDFLAGS="-arch x86_64 -arch=arm64e" ./configure`

**Comment by ldzhjn** [comment]
> > have 'arm64e', need 'x86_64'
> 
> this is the reason. your "kafka" binary is compiled for intel and executed via rosetta binary translation. therefore arm64e proxychains cant be injected.
> 
> 2 solutions exist:
> 
> * get a kafka version compiled for m1
> * make a fat binary for x86_64 and arm64e: it should work like this: `CFLAGS="-arch x86_64 -arch=arm64e" LDFLAGS="-arch x86_64 -arch=arm64e" ./configure`

Tried both solutions, both worked.
