### ISSUE TITLE
Warning: You are using OS X 10.11.

### ISSUE THREAD

**Issue by wedojava** [rofl0r/proxychains-ng#97]
I have readed the issues:Error on OS X 10.11 #74, and do this two step:
1. i run this:`xcode-select -s /Applications/Xcode6-Beta3.app/Contents/Developer`
2. run `brew install proxychains-ng`

and than, it still warning. What Can I Do? Please Help Me.Thanks!

```
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Downloading https://downloads.sourceforge.net/project/proxychains-ng/proxych
Already downloaded: /Library/Caches/Homebrew/proxychains-ng-4.10.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/proxychains-ng/4.10 --sysconfdir=/usr
==> make
make: *** [src/allocator_thread.o] Error 1
1 error generated.
make: *** [src/libproxychains.o] Error 1
1 error generated.
make: *** [src/core.o] Error 1

READ THIS: https://git.io/brew-troubleshooting

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize': Operation timed out - connect(2) (Errno::ETIMEDOUT)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:313:in `open_http'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
	from /usr/local/Library/Homebrew/utils.rb:404:in `open'
	from /usr/local/Library/Homebrew/utils.rb:434:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:466:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:209:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:205:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:248:in `dump'
	from /usr/local/Library/brew.rb:154:in `rescue in <main>'
	from /usr/local/Library/brew.rb:67:in `<main>'
```

**Comment by rofl0r** [comment]
i can't help you with this since i dont own a mac, and this is an issue with homebrew (error in their recipe or your setup), so please ask there.
